Dylan Ross

Select out subsets of the omics data based on targeted pairwise comparisons:
- Black patients: NPM1 mutant vs. WT
- White patients: NPM1 mutant vs. WT
- Black patients: NRAS mutant vs. WT
- White patients: NRAS mutant vs. WT

## Setup

### Imports

In [1]:
import os
from typing import List
import pickle

import polars as pl
from scipy import stats
from plotly import graph_objects as pgo

### Constants

In [2]:
# Jupyter server should be running from src/python
CACHE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.getcwd())),
    "analysis",
    "dylan",
    "_cache"
)

FIGURE_DIR = os.path.join(
    os.path.dirname(os.path.dirname(os.getcwd())),
    "analysis",
    "dylan",
    "_figures"
)

# cached metadata table 
META_CACHE = os.path.join(CACHE_DIR, "meta.arrow")
OMICS_CACHE = os.path.join(CACHE_DIR, "combined.arrow")

# missingness threshold (as a proportion) for dropping omics data rows
# rows with missingness above this threshold are dropped
MISSING_THRESHOLD = 0.3

### Load metadata and omics data from cache

In [3]:
meta = pl.read_ipc(META_CACHE)
meta

shape: (284, 9)
┌─────────────────┬──────┬────────┬───────┬───┬──────────┬───────────┬───────┬───────┐
│ Sample          ┆ Age  ┆ Sex    ┆ Race  ┆ … ┆ FLT3_ITD ┆ IDH1+IDH2 ┆ NPM1  ┆ NRAS  │
│ ---             ┆ ---  ┆ ---    ┆ ---   ┆   ┆ ---      ┆ ---       ┆ ---   ┆ ---   │
│ str             ┆ f64  ┆ str    ┆ str   ┆   ┆ bool     ┆ bool      ┆ bool  ┆ bool  │
╞═════════════════╪══════╪════════╪═══════╪═══╪══════════╪═══════════╪═══════╪═══════╡
│ 11-00261        ┆ 74.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ false ┆ false │
│ 11-00503        ┆ 54.0 ┆ Female ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 11-00475        ┆ 65.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 12-00032        ┆ 70.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ false ┆ false │
│ 11-00376        ┆ 49.0 ┆ Male   ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ …               ┆ …    ┆ …      ┆ …     ┆ … ┆ …        ┆ …         ┆ …     ┆ …     │
│ 16-01109-Bridge ┆ 33.0 ┆ Male   ┆ Black ┆ … ┆ false    ┆ false     ┆ false ┆ false │
│ 16-01191-Bridge ┆ 65.0 ┆ Female ┆ White ┆ … ┆ false    ┆ false     ┆ false ┆ true  │
│ 17-00025-Bridge ┆ 39.0 ┆ Female ┆ White ┆ … ┆ true     ┆ false     ┆ true  ┆ false │
│ 17-00741-Bridge ┆ 20.0 ┆ Male   ┆ White ┆ … ┆ false    ┆ false     ┆ true  ┆ true  │
│ 17-00881-Bridge ┆ 76.0 ┆ Female ┆ White ┆ … ┆ false    ┆ false     ┆ false ┆ false │
└─────────────────┴──────┴────────┴───────┴───┴──────────┴───────────┴───────┴───────┘

In [4]:
combined = pl.read_ipc(OMICS_CACHE)
combined

shape: (34_470, 286)
┌────────────┬───────────┬──────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Block      ┆ Feature   ┆ 11-00261 ┆ 11-00503 ┆ … ┆ 16-01191- ┆ 17-00025- ┆ 17-00741- ┆ 17-00881- │
│ ---        ┆ ---       ┆ ---      ┆ ---      ┆   ┆ Bridge    ┆ Bridge    ┆ Bridge    ┆ Bridge    │
│ str        ┆ str       ┆ f64      ┆ f64      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆           ┆          ┆          ┆   ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪═══════════╪══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Acetylomic ┆ A2M-K1176 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ k         ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ A2M-K912k ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABCE1-K34 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 3k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABCE1-K43 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 1k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Acetylomic ┆ ABHD10-K6 ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ s          ┆ 9k        ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …        ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Transcript ┆ CEP43__2  ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ C2orf15   ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ GRIN2B    ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ SNURF     ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆           ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
│ Transcript ┆ C1QTNF3-A ┆ null     ┆ null     ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ omics      ┆ MACR      ┆          ┆          ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴──────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
# report on the number of features in each block
combined.group_by("Block").len().sort("len", descending=True)

shape: (6, 2)
┌───────────────────┬───────┐
│ Block             ┆ len   │
│ ---               ┆ ---   │
│ str               ┆ u32   │
╞═══════════════════╪═══════╡
│ Transcriptomics   ┆ 14372 │
│ Phosphoproteomics ┆ 8362  │
│ Proteomics        ┆ 8059  │
│ Acetylomics       ┆ 3285  │
│ Lipidomics        ┆ 343   │
│ Metabolomics      ┆ 49    │
└───────────────────┴───────┘

## Create Subsets

### Utility function for selecting subsets and applying transformations/normalizations
- filter columns to only include the selected samples for the subset (with two sample groups)
- filter rows separately for each sample group to remove rows with missingness fraction greater than a specified threshold
- impute remaining missing values across all subset samples with row median
- apply row-wise z-score normalization across subset samples

In [6]:
def select_subset(
    combined: pl.DataFrame,
    wt_cols: List[str],
    mut_cols: List[str]
) -> pl.DataFrame :
    """
    Select a subset of the combined -omics data DataFrame that contains a specified
    set of samples belonging to WT/mutant groups. Filters rows based on a missingness
    threshold, imputes remaining missing values with row median, then applies a 
    row-wise z-score normalization to the full table. Returns the processed DataFrame
    with the selected subset.
    """
    return (
        combined
        .select(
            "Block",
            "Feature",
            *wt_cols,
            *mut_cols
        )
        .filter(
            # filter out rows where missingness within WT or mut sample groups
            # is greater than missingness threshold
            ((pl.sum_horizontal(pl.col(wt_cols).is_null()) / len(wt_cols)) <= MISSING_THRESHOLD) 
            & ((pl.sum_horizontal(pl.col(mut_cols).is_null()) / len(mut_cols)) <= MISSING_THRESHOLD)
        )
        .with_columns(
            # add a column with the row median
            pl.concat_list(wt_cols + mut_cols)
            .list.median()
            .alias("row_median")
        )
        .select(
            "Block",
            "Feature",
            (
                # pack the raw values into a list column
                pl.concat_list(
                    pl.col(wt_cols + mut_cols)
                    # fill null values with row median
                    .fill_null(pl.col("row_median"))
                )
                # compute row-wise z-scores
                .map_elements(
                    stats.zscore, 
                    return_dtype=pl.List(pl.Float64)
                )
                # convert list to struct 
                .list.to_struct(
                    fields=wt_cols + mut_cols
                )
                .alias("packed")
            )
        )
        # unpack struct with z-scores back to sample columns
        .unnest("packed")
    )

### Utility function to plot feature counts from the -omics data blocks before/after subsetting

In [19]:
def plot_filtered_feature_counts(
    combined: pl.DataFrame, 
    subset: pl.DataFrame, 
    figname=None
) :
    # key: block label
    # value: color
    colors = {
        "Transcriptomics": "#EF476F",
        "Phosphoproteomics": "#F7866B",
        "Proteomics": "#FFD166",
        "Acetylomics": "#06D6A0",
        "Lipidomics": "#11A2B2",
        "Metabolomics": "#0B6584",
        "Filtered": "#444444"
    }

    def _hex_to_rgba(hex: str, alpha: float) -> str : 
        """ add some transparency to rgb hex code and format it how plotly likes it """
        # assume the hex string starts with #
        ir = int(hex[1:3], 16)
        ig = int(hex[3:5], 16)
        ib = int(hex[5:7], 16)
        return f"rgba({ir}, {ig}, {ib}, {alpha})"

    # feature counts 
    counts = (
        combined
        .group_by("Block").len()
        .rename({"len": "pre"})
        .join(
            (
                subset
                .group_by("Block").len()
                .rename({"len": "post"})
            ), 
            how="left", 
            on="Block"
        )
        .fill_null(0)
        .sort("pre", descending=True)
    )

    # node: 
    #   key: {
    #       "index": index, 
    #       "color": color, 
    #       "label": label
    #       "count": count 
    #       "filtered": label <- for source nodes only
    # }
    node_data = {}

    # construct the node data from feature counts pre- and post-subsetting
    i = 0
    filtered = 0
    for block, pre, post in counts.iter_rows() :
        # add the node for pre-subsetting feature count
        node_data[f"{block}_0"] = {
            "index": i,
            "color": colors[block],
            "label": f"{block} ({pre})",
            "count": pre,
            "filtered": pre - post
        }
        filtered += pre - post
        i += 1
        # add the node for post-subsetting feature count
        node_data[f"{block}_1"] = {
            "index": i,
            "color": colors[block],
            "label": f"({post}) {block}",
            "count": post
        }
        i += 1

    # add a catch-all node for features that were filtered out
    node_data["Filtered"] = {
        "index": i,
        "color": colors["Filtered"],
        "label": f"({filtered}) Filtered",
        "count": filtered
    }

    # construct the link data from the node data
    link_data = {"source": [], "target": [], "value": [], "color": []}
    for block, pre, post in counts.iter_rows():
        # if features for a given block remained after subsetting, add a link
        if post > 0:
            link_data["source"].append(node_data[f"{block}_0"]["index"])
            link_data["target"].append(node_data[f"{block}_1"]["index"])
            link_data["value"].append(node_data[f"{block}_1"]["count"])
            link_data["color"].append(_hex_to_rgba(node_data[f"{block}_0"]["color"], 0.25))
        # always add the link from the block to filtered node
        link_data["source"].append(node_data[f"{block}_0"]["index"])
        link_data["target"].append(node_data["Filtered"]["index"])
        link_data["value"].append(node_data[f"{block}_0"]["filtered"])
        link_data["color"].append(_hex_to_rgba(node_data["Filtered"]["color"], 0.25))

        fig = pgo.Figure(
        data=[
            pgo.Sankey(
                arrangement="freeform",
                node=dict(
                    pad=15,
                    thickness=20,
                    line=dict(color="black", width=0.75),
                    label=[v["label"] for v in sorted(node_data.values(), key=lambda x: x["index"])],
                    color=[v["color"] for v in sorted(node_data.values(), key=lambda x: x["index"])],
                ),
                link=link_data
            )
        ]
    )
    if figname is not None:
        fig.write_image(figname, width=600, height=350, scale=4)
    fig.show()

### NPM1 vs. WT
#### Black patients

In [20]:
# select the sample columns
# WT
wt_cols = meta.filter(
    (pl.col("Race") == "Black")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{wt_cols=}")
# NPM1
mut_cols = meta.filter(
    (pl.col("Race") == "Black")
    & pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{mut_cols=}")

# save the sample columns
with open(os.path.join(CACHE_DIR, "B_NPM1-WT_cols.pkl"), "wb") as pf:
    pickle.dump((wt_cols, mut_cols), pf)

# subset the omics data
subset = select_subset(combined, wt_cols, mut_cols)

# save the subset to file
subset.write_ipc(os.path.join(CACHE_DIR, "B_NPM1-WT.arrow"))

# display
display(subset)

# report on the number of features in each block
subset.group_by("Block").len().sort("len", descending=True)

# plot feature counts before/after subsetting
plot_filtered_feature_counts(
    combined,
    subset,
    figname=os.path.join(FIGURE_DIR, "block-feature-counts_B_NPM1-WT.png")
)

wt_cols=['14-00240', '16-00538', '16-01109', '17-01060', 'C-05-0664', 'C-04-1820', 'C-07-3682', 'C-10-1211', 'C-10-3429', 'C-08-2091', 'C-13-0276', 'C-08-3337', 'C-10-3924', 'C-09-3512', 'C-09-5462', 'C-08-3493', 'C-04-3407', 'C-09-1074', 'C-09-4769', 'C-10-3906', 'C-07-2070', 'C-05-2179', 'C-05-2448', 'C-07-2900', '94-C-279', 'C-09-1608', 'C-02-0218', 'C-96-117', 'C-95-054', 'C-12-4258', 'C-10-0773', 'C-00-0552', 'C-11-5466', 'C-10-0535', 'C-98-0454', 'C-99-0901', 'C-03-2056', 'C-10-0302', 'C-01-1599', 'C-08-2081', 'C-09-0923', '93-C-201', 'C-01-1998', 'C-99-2136', 'C-05-1782', 'PS88-0050', 'C-01-2163', 'C-02-0350', 'C-01-0171', 'C-99-1077', 'C-05-0004', 'C-05-4372', 'PS89-0158', '94-C-077', 'C-98-0033', 'C-98-0665', 'C-02-1356', '16-01109-Bridge']
mut_cols=['16-00611', '16-01267', 'C-00-1828', 'C-08-0176', 'C-97-0509', 'C-09-1336', 'C-05-3084']

shape: (12_354, 67)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 14-00240  ┆ 16-00538  ┆ … ┆ C-08-0176 ┆ C-97-0509 ┆ C-09-1336 ┆ C-05-308 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 4        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Lipidomic ┆ neg_LPI   ┆ 0.037803  ┆ 0.015719  ┆ … ┆ -0.066051 ┆ -1.137861 ┆ 0.962647  ┆ 0.161951 │
│ s         ┆ 20:4_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ 1.106777  ┆ 0.157645  ┆ … ┆ 0.335503  ┆ -0.420464 ┆ 0.15376   ┆ -1.44599 │
│ s         ┆ 22:6_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPG   ┆ -1.003826 ┆ 0.088184  ┆ … ┆ 0.676836  ┆ 0.408397  ┆ 1.333626  ┆ -0.38684 │
│ s         ┆ 22:5_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPS   ┆ 0.18351   ┆ -0.190818 ┆ … ┆ -0.29137  ┆ -0.403257 ┆ -0.15379  ┆ -0.72504 │
│ s         ┆ 18:1_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Lipidomic ┆ neg_LPI   ┆ -0.538562 ┆ -0.003494 ┆ … ┆ -1.276946 ┆ -1.582877 ┆ 0.159277  ┆ 0.024388 │
│ s         ┆ 22:4_[M-H ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆ ]-__A     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Phosphopr ┆ ZSWIM8-S4 ┆ 0.271383  ┆ -0.273407 ┆ … ┆ -0.10966  ┆ -2.295714 ┆ -1.919116 ┆ -1.13434 │
│ oteomics  ┆ 8s        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZYX-S267s ┆ 0.323496  ┆ 1.453069  ┆ … ┆ -0.020934 ┆ -1.918101 ┆ -1.466257 ┆ -1.12459 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Phosphopr ┆ ZYX-S281s ┆ -0.31177  ┆ 0.256307  ┆ … ┆ -0.200658 ┆ -1.671553 ┆ -0.291953 ┆ -0.92928 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
│ Phosphopr ┆ ZYX-S344s ┆ 0.274056  ┆ 1.987247  ┆ … ┆ -0.1447   ┆ -1.812413 ┆ -1.202274 ┆ -0.81173 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Phosphopr ┆ ZZEF1-S15 ┆ -1.690985 ┆ 0.704832  ┆ … ┆ 0.08853   ┆ -2.513782 ┆ 0.352121  ┆ -0.39111 │
│ oteomics  ┆ 18s       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
(
    combined
    .group_by("Block").len()
    .rename({"len": "pre"})
    .join(
        (
            subset
            .group_by("Block").len()
            .rename({"len": "post"})
        ), 
        how="left", 
        on="Block"
    )
    .fill_null(0)
    .sort("pre", descending=True)
)

shape: (6, 3)
┌───────────────────┬───────┬──────┐
│ Block             ┆ pre   ┆ post │
│ ---               ┆ ---   ┆ ---  │
│ str               ┆ u32   ┆ u32  │
╞═══════════════════╪═══════╪══════╡
│ Transcriptomics   ┆ 14372 ┆ 0    │
│ Phosphoproteomics ┆ 8362  ┆ 4539 │
│ Proteomics        ┆ 8059  ┆ 7441 │
│ Acetylomics       ┆ 3285  ┆ 0    │
│ Lipidomics        ┆ 343   ┆ 325  │
│ Metabolomics      ┆ 49    ┆ 49   │
└───────────────────┴───────┴──────┘

#### White patients

In [22]:
# select the sample columns
# WT
wt_cols = meta.filter(
    (pl.col("Race") == "White")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{wt_cols=}")
# NPM1
mut_cols = meta.filter(
    (pl.col("Race") == "White")
    & pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{mut_cols=}")

# save the sample columns
with open(os.path.join(CACHE_DIR, "W_NPM1-WT_cols.pkl"), "wb") as pf:
    pickle.dump((wt_cols, mut_cols), pf)

# subset the omics data
subset = select_subset(combined, wt_cols, mut_cols)

# save the subset to file
subset.write_ipc(os.path.join(CACHE_DIR, "W_NPM1-WT.arrow"))

# display
display(subset)

# report on the number of features in each block
subset.group_by("Block").len().sort("len", descending=True)

# plot feature counts before/after subsetting
plot_filtered_feature_counts(
    combined,
    subset,
    figname=os.path.join(FIGURE_DIR, "block-feature-counts_W_NPM1-WT.png")
)

wt_cols=['13-00033', '13-00034', '13-00077', '13-00149', '13-00160', '13-00186', '13-00226', '13-00468', '13-00558', '13-00602', '14-00528', '14-00423', '14-00434', '14-00514', '14-00608', '14-00613', '14-00711', '15-00043', '15-00888', '15-00137', '15-00287', '15-00563', '15-00742', '15-00777', '15-00837', '15-00870', '16-00001', '16-00094', '16-00306', '16-00351', '16-00354', '16-00479', '16-00481', '16-00494', '16-00519', '16-00627', '16-00882', '16-00818', '18-00149', '16-01004', '16-01102', '16-01201', '16-01270', '17-00322', '17-00325', '17-00328', '18-00251', '17-00500', '17-00678', '17-00676', '17-00763', '17-00878', '17-00881', '17-00896', '18-00103', '18-00105', '18-00190', '18-00203', '18-00218', '18-00290', '18-00414', '19-00084', '14-00126', '17-00649', '14-00528-Bridge', '16-00494-Bridge', '16-00627-Bridge', '17-00881-Bridge']
mut_cols=['12-00127', '13-00123', '13-00157', '13-00195', '13-00331', '15-00482', '15-00051', '15-00276', '15-00302', '15-00653', '15-00855', '16-00056', '16-00886', '16-00504', '16-01061', '16-01100', '16-01151', '16-01227', '17-00021', '17-00361', '17-00444', '17-00689', '17-00770', '17-00834', '17-01054', '19-00092', '16-01100-Bridge']

shape: (28_150, 97)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 13-00033  ┆ 13-00034  ┆ … ┆ 17-00834  ┆ 17-01054  ┆ 19-00092  ┆ 16-01100 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ -Bridge  │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Proteomic ┆ A1BG      ┆ -1.120712 ┆ 0.559693  ┆ … ┆ 2.123743  ┆ -1.570688 ┆ -0.158679 ┆ -0.72956 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Proteomic ┆ A2M       ┆ -0.645049 ┆ 1.652101  ┆ … ┆ 0.912377  ┆ -0.551094 ┆ -0.814283 ┆ -0.36181 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ Proteomic ┆ AAAS      ┆ 0.030761  ┆ 1.399064  ┆ … ┆ 0.686234  ┆ -1.342254 ┆ -0.947444 ┆ 0.503089 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Proteomic ┆ AACS      ┆ 0.07813   ┆ 1.898765  ┆ … ┆ 0.944014  ┆ 0.197232  ┆ -0.234734 ┆ 2.155406 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Proteomic ┆ AAGAB     ┆ -0.007986 ┆ 1.871435  ┆ … ┆ 0.670166  ┆ -1.292822 ┆ -0.798046 ┆ 1.20724  │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Transcrip ┆ CEP43__2  ┆ -0.339774 ┆ -1.193835 ┆ … ┆ -0.476439 ┆ 0.883741  ┆ 3.301997  ┆ -0.33977 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ Transcrip ┆ C2orf15   ┆ -0.200779 ┆ -0.33714  ┆ … ┆ 0.262926  ┆ 1.313944  ┆ 3.094398  ┆ -0.20077 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9        │
│ Transcrip ┆ GRIN2B    ┆ -0.465992 ┆ -0.465992 ┆ … ┆ -0.465992 ┆ -0.465992 ┆ -0.465992 ┆ -0.46599 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2        │
│ Transcrip ┆ SNURF     ┆ -0.300535 ┆ -0.875002 ┆ … ┆ -0.53808  ┆ 3.808483  ┆ -0.434352 ┆ -0.30053 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ Transcrip ┆ C1QTNF3-A ┆ -0.269677 ┆ -0.971184 ┆ … ┆ -1.432137 ┆ 2.653031  ┆ 3.452123  ┆ -0.26967 │
│ tomics    ┆ MACR      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 7        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### NRAS vs. WT
#### Black patients

In [23]:
# select the sample columns
# WT
wt_cols = meta.filter(
    (pl.col("Race") == "Black")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{wt_cols=}")
# NRAS
mut_cols = meta.filter(
    (pl.col("Race") == "Black")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & pl.col("NRAS")
)["Sample"].to_list()
print(f"{mut_cols=}")

# save the sample columns
with open(os.path.join(CACHE_DIR, "B_NRAS-WT_cols.pkl"), "wb") as pf:
    pickle.dump((wt_cols, mut_cols), pf)

# subset the omics data
subset = select_subset(combined, wt_cols, mut_cols)

# save the subset to file
subset.write_ipc(os.path.join(CACHE_DIR, "B_NRAS-WT.arrow"))

# display
display(subset)

# report on the number of features in each block
subset.group_by("Block").len().sort("len", descending=True)

# plot feature counts before/after subsetting
plot_filtered_feature_counts(
    combined,
    subset,
    figname=os.path.join(FIGURE_DIR, "block-feature-counts_B_NRAS-WT.png")
)

wt_cols=['14-00240', '16-00538', '16-01109', '17-01060', 'C-05-0664', 'C-04-1820', 'C-07-3682', 'C-10-1211', 'C-10-3429', 'C-08-2091', 'C-13-0276', 'C-08-3337', 'C-10-3924', 'C-09-3512', 'C-09-5462', 'C-08-3493', 'C-04-3407', 'C-09-1074', 'C-09-4769', 'C-10-3906', 'C-07-2070', 'C-05-2179', 'C-05-2448', 'C-07-2900', '94-C-279', 'C-09-1608', 'C-02-0218', 'C-96-117', 'C-95-054', 'C-12-4258', 'C-10-0773', 'C-00-0552', 'C-11-5466', 'C-10-0535', 'C-98-0454', 'C-99-0901', 'C-03-2056', 'C-10-0302', 'C-01-1599', 'C-08-2081', 'C-09-0923', '93-C-201', 'C-01-1998', 'C-99-2136', 'C-05-1782', 'PS88-0050', 'C-01-2163', 'C-02-0350', 'C-01-0171', 'C-99-1077', 'C-05-0004', 'C-05-4372', 'PS89-0158', '94-C-077', 'C-98-0033', 'C-98-0665', 'C-02-1356', '16-01109-Bridge']
mut_cols=['C-98-0846', 'C-09-1906', 'C-05-1287', 'C-04-1098', 'C-09-5381', 'C-05-0569', 'C-04-1647', 'C-99-0740', 'C-12-2943', 'C-95-068', 'C-01-1665', 'C-05-3159', 'C-98-0031']

shape: (15_154, 73)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 14-00240  ┆ 16-00538  ┆ … ┆ C-95-068  ┆ C-01-1665 ┆ C-05-3159 ┆ C-98-003 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 1        │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Acetylomi ┆ ABCE1-K43 ┆ 0.001422  ┆ 0.001422  ┆ … ┆ -0.904046 ┆ 2.001628  ┆ -0.072301 ┆ 0.855812 │
│ cs        ┆ 1k        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ACAA2-K13 ┆ -0.105592 ┆ -0.105592 ┆ … ┆ 0.235691  ┆ 0.394843  ┆ -1.908605 ┆ -0.34615 │
│ cs        ┆ 7k        ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ Acetylomi ┆ ACAA2-K20 ┆ 0.102067  ┆ 0.102067  ┆ … ┆ 0.107032  ┆ -1.253671 ┆ -2.356755 ┆ -0.24376 │
│ cs        ┆ 9k        ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Acetylomi ┆ ACAA2-K23 ┆ -0.08221  ┆ -0.08221  ┆ … ┆ -0.579465 ┆ 0.243256  ┆ -1.657397 ┆ 0.357634 │
│ cs        ┆ 4k        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Acetylomi ┆ ACAA2-K26 ┆ 0.105122  ┆ 0.105122  ┆ … ┆ 0.130108  ┆ 0.105122  ┆ -1.726699 ┆ -1.05861 │
│ cs        ┆ 9k        ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Phosphopr ┆ ZYX-S267s ┆ 0.319582  ┆ 1.443436  ┆ … ┆ 0.398485  ┆ 2.079636  ┆ 0.635231  ┆ 0.129535 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZYX-S281s ┆ -0.294124 ┆ 0.242154  ┆ … ┆ 0.164558  ┆ 2.61484   ┆ 0.425631  ┆ 1.188071 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZYX-S308s ┆ -0.684981 ┆ 1.880521  ┆ … ┆ -1.126367 ┆ 0.417205  ┆ 1.473846  ┆ -0.00705 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1        │
│ Phosphopr ┆ ZYX-S344s ┆ 0.288289  ┆ 1.985384  ┆ … ┆ 0.039818  ┆ 2.035949  ┆ 0.321055  ┆ 0.765993 │
│ oteomics  ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phosphopr ┆ ZZZ3-S113 ┆ -0.038272 ┆ 0.236892  ┆ … ┆ 0.218483  ┆ -2.026567 ┆ -0.525829 ┆ 2.515754 │
│ oteomics  ┆ s         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### White patients

In [24]:
# select the sample columns
# WT
wt_cols = meta.filter(
    (pl.col("Race") == "White")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & ~pl.col("NRAS")
)["Sample"].to_list()
print(f"{wt_cols=}")
# NRAS
mut_cols = meta.filter(
    (pl.col("Race") == "White")
    & ~pl.col("NPM1")
    & ~pl.col("FLT3_ITD")
    & ~pl.col("IDH1+IDH2")
    & pl.col("NRAS")
)["Sample"].to_list()
print(f"{mut_cols=}")

# save the sample columns
with open(os.path.join(CACHE_DIR, "W_NRAS-WT_cols.pkl"), "wb") as pf:
    pickle.dump((wt_cols, mut_cols), pf)

# subset the omics data
subset = select_subset(combined, wt_cols, mut_cols)

# save the subset to file
subset.write_ipc(os.path.join(CACHE_DIR, "W_NRAS-WT.arrow"))

# display
display(subset)

# report on the number of features in each block
subset.group_by("Block").len().sort("len", descending=True)

# plot feature counts before/after subsetting
plot_filtered_feature_counts(
    combined,
    subset,
    figname=os.path.join(FIGURE_DIR, "block-feature-counts_W_NRAS-WT.png")
)

wt_cols=['13-00033', '13-00034', '13-00077', '13-00149', '13-00160', '13-00186', '13-00226', '13-00468', '13-00558', '13-00602', '14-00528', '14-00423', '14-00434', '14-00514', '14-00608', '14-00613', '14-00711', '15-00043', '15-00888', '15-00137', '15-00287', '15-00563', '15-00742', '15-00777', '15-00837', '15-00870', '16-00001', '16-00094', '16-00306', '16-00351', '16-00354', '16-00479', '16-00481', '16-00494', '16-00519', '16-00627', '16-00882', '16-00818', '18-00149', '16-01004', '16-01102', '16-01201', '16-01270', '17-00322', '17-00325', '17-00328', '18-00251', '17-00500', '17-00678', '17-00676', '17-00763', '17-00878', '17-00881', '17-00896', '18-00103', '18-00105', '18-00190', '18-00203', '18-00218', '18-00290', '18-00414', '19-00084', '14-00126', '17-00649', '14-00528-Bridge', '16-00494-Bridge', '16-00627-Bridge', '17-00881-Bridge']
mut_cols=['14-00127', '14-00193', '14-00712', '15-00377', '15-00578', '15-00813', '15-00976', '16-00751', '16-01191', '16-01220', '17-00072', '17-00901', '18-00408', '16-01191-Bridge']

shape: (28_104, 84)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Block     ┆ Feature   ┆ 13-00033  ┆ 13-00034  ┆ … ┆ 17-00072  ┆ 17-00901  ┆ 18-00408  ┆ 16-01191 │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ -Bridge  │
│ str       ┆ str       ┆ f64       ┆ f64       ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Proteomic ┆ A1BG      ┆ -1.121872 ┆ 0.595768  ┆ … ┆ -0.112906 ┆ -0.048434 ┆ -0.048434 ┆ 0.956138 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Proteomic ┆ A2M       ┆ -0.65365  ┆ 1.698652  ┆ … ┆ -0.591918 ┆ 1.040626  ┆ 0.094029  ┆ -0.38881 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Proteomic ┆ AAAS      ┆ 0.064053  ┆ 1.430991  ┆ … ┆ 0.725258  ┆ 0.518186  ┆ -1.455829 ┆ -1.80406 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4        │
│ Proteomic ┆ AACS      ┆ 0.170445  ┆ 2.119524  ┆ … ┆ 0.418716  ┆ 2.244499  ┆ -0.256737 ┆ 0.765562 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Proteomic ┆ AAGAB     ┆ -0.00279  ┆ 1.917118  ┆ … ┆ 0.459879  ┆ 1.136976  ┆ -1.443272 ┆ -0.53420 │
│ s         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 5        │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Transcrip ┆ CEP43__2  ┆ -0.31631  ┆ -1.181159 ┆ … ┆ -0.331372 ┆ 1.263328  ┆ 0.383668  ┆ -0.31631 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Transcrip ┆ C2orf15   ┆ -0.104533 ┆ -0.260968 ┆ … ┆ 1.325014  ┆ -0.759824 ┆ -0.267308 ┆ -0.10453 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Transcrip ┆ GRIN2B    ┆ -0.359796 ┆ -0.359796 ┆ … ┆ -0.359796 ┆ -0.359796 ┆ -0.359796 ┆ -0.35979 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 6        │
│ Transcrip ┆ SNURF     ┆ -0.296463 ┆ -0.915703 ┆ … ┆ -0.069135 ┆ -0.109929 ┆ -0.280857 ┆ -0.29646 │
│ tomics    ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3        │
│ Transcrip ┆ C1QTNF3-A ┆ -0.170448 ┆ -1.035642 ┆ … ┆ -0.704972 ┆ -1.2      ┆ -0.58521  ┆ -0.17044 │
│ tomics    ┆ MACR      ┆           ┆           ┆   ┆           ┆           ┆           ┆ 8        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘